# Generated by Django 5.2.4 on 2025-07-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parte', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('importe', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
