# Generated by Django 5.2.4 on 2025-07-19 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0005_accesorio_cliente_unidad_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parte', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_cumple',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
