# Generated by Django 5.2.4 on 2025-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0006_indumentaria_cliente_fecha_cumple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='modelo',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='num_parte',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
